name: "publish"

on:
  push:
    branches:
      - main

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
            args: "--target aarch64-apple-darwin"
          - platform: "macos-15-intel"
            args: "--target x86_64-apple-darwin"
          - platform: "ubuntu-latest"
            args: ""
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Check for changes
        id: changed_src_files
        uses: tj-actions/changed-files@v46
        with:
          files: |
            src/**
            src-tauri/**

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libmpv-dev
          echo

      - name: install dependencies (mac only)
        if: contains(matrix.platform, 'macos')
        run: |
          brew update
          brew install mpv pkg-config

      - name: install dependencies (windows only)
        if: matrix.platform == 'windows-latest'
        run: |
          choco install 7zip -y
          curl -L -o mpv-dev.7z https://github.com/zhongfly/mpv-winbuild/releases/download/2026-01-08-85bf9f4/mpv-dev-x86_64-20260108-git-85bf9f4.7z
          7z x mpv-dev.7z -oC:\mpv-dev
          ren C:\mpv-dev\libmpv.dll.a C:\mpv-dev\mpv.lib
          echo "MPV_SOURCE=C:\mpv-dev" >> $env:GITHUB_ENV
          echo "C:\mpv-dev" >> $env:GITHUB_PATH

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin' || matrix.platform == 'macos-15-intel' && 'x86_64-apple-darwin' || '' }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: install frontend dependencies
        run: bun install

      - name: import Apple Developer Certificate
        if: contains(matrix.platform, 'macos')
        env:
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          echo $APPLE_CERTIFICATE | base64 --decode > certificate.p12
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security set-keychain-settings -t 3600 -u build.keychain
          security import certificate.p12 -k build.keychain -P "$APPLE_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" build.keychain
          security find-identity -v -p codesigning build.keychain

      - name: verify certificate
        if: contains(matrix.platform, 'macos')
        run: |
          CERT_INFO=$(security find-identity -v -p codesigning build.keychain | grep "Developer ID Application")
          CERT_ID=$(echo "$CERT_INFO" | awk -F'"' '{print $2}')
          echo "CERT_ID=$CERT_ID" >> $GITHUB_ENV
          echo "Certificate imported."

      - name: set build paths (mac only)
        if: contains(matrix.platform, 'macos')
        run: |
          BREW_PREFIX=$(brew --prefix)
          echo "LIBRARY_PATH=$BREW_PREFIX/lib:$LIBRARY_PATH" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=$BREW_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
      - name: build and publish
        uses: tauri-apps/tauri-action@v0.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
          LASTFM_API_SECRET: ${{ secrets.LASTFM_API_SECRET }}
          TIDAL_CLIENT_ID: ${{ secrets.TIDAL_CLIENT_ID }}
          TIDAL_CLIENT_SECRET: ${{ secrets.TIDAL_CLIENT_SECRET }}
          MPV_SOURCE: ${{ env.MPV_SOURCE}}
          PKG_CONFIG_PATH: ${{env.PKG_CONFIG_PATH}}
          LIBRARY_PATH: ${{env.LIBRARY_PATH}}
          APPLE_ID: ${{ contains(matrix.platform, 'macos') && secrets.APPLE_ID || '' }}
          APPLE_PASSWORD: ${{ contains(matrix.platform, 'macos') && secrets.APPLE_PASSWORD || '' }}
          APPLE_TEAM_ID: ${{ contains(matrix.platform, 'macos') && secrets.APPLE_TEAM_ID || '' }}
          APPLE_CERTIFICATE: ${{ contains(matrix.platform, 'macos') && secrets.APPLE_CERTIFICATE || '' }}
          APPLE_CERTIFICATE_PASSWORD: ${{ contains(matrix.platform, 'macos') && secrets.APPLE_CERTIFICATE_PASSWORD || '' }}
          APPLE_SIGNING_IDENTITY: ${{ contains(matrix.platform, 'macos') && env.CERT_ID || '' }}
        with:
          tagName: app-v__VERSION__
          releaseName: "Aether Player v__VERSION__"
          releaseDraft: false
          prerelease: false
          includeUpdaterJson: true
          generateReleaseNotes: true
          args: ${{ matrix.args }}
